"""add_librenms_link_to_devices

Revision ID: 1751a813079b
Revises: cad291b934e2
Create Date: 2025-12-29 09:52:31.743726

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1751a813079b"
down_revision: Union[str, Sequence[str], None] = "cad291b934e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "devices", sa.Column("librenms_device_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "devices", sa.Column("librenms_hostname", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "devices",
        sa.Column("librenms_last_synched", sa.DateTime(timezone=True), nullable=True),
    )
    op.alter_column("devices", "location_id", existing_type=sa.INTEGER(), nullable=True)
    op.create_index(
        op.f("ix_devices_librenms_device_id"),
        "devices",
        ["librenms_device_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_devices_librenms_hostname"),
        "devices",
        ["librenms_hostname"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_devices_librenms_hostname"), table_name="devices")
    op.drop_index(op.f("ix_devices_librenms_device_id"), table_name="devices")
    op.alter_column(
        "devices", "location_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_column("devices", "librenms_last_synced")
    op.drop_column("devices", "librenms_hostname")
    op.drop_column("devices", "librenms_device_id")
    # ### end Alembic commands ###
