"""add min minutes duration for top down

Revision ID: 2b7f1af7699c
Revises: 4a95a8d677b5
Create Date: 2026-05-18 11:57:45.216134

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2b7f1af7699c"
down_revision: Union[str, Sequence[str], None] = "4a95a8d677b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "system_config",
        sa.Column(
            "top_down_min_alert_duration_minutes",
            sa.Integer(),
            server_default="30",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("system_config", "top_down_min_alert_duration_minutes")
    # ### end Alembic commands ###
