"""Add status history index

Revision ID: 4a95a8d677b5
Revises: b98ecd2c152b
Create Date: 2026-05-11 13:53:14.609619

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4a95a8d677b5"
down_revision: Union[str, Sequence[str], None] = "b98ecd2c152b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_status_history_node_time",
        "status_history",
        ["node_type", "node_id", "changed_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_status_history_node_time", table_name="status_history")
    # ### end Alembic commands ###
