"""add parent_id column in location group table

Revision ID: 520d3574538a
Revises: 987383d25581
Create Date: 2026-04-22 13:24:24.213401

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "520d3574538a"
down_revision: Union[str, Sequence[str], None] = "987383d25581"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "location_groups", sa.Column("parent_id", sa.Integer(), nullable=True)
    )
    op.create_index(
        op.f("ix_location_groups_parent_id"),
        "location_groups",
        ["parent_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_location_groups_parent_id",
        "location_groups",
        "location_groups",
        ["parent_id"],
        ["group_id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_location_groups_parent_id", "location_groups", type_="foreignkey"
    )
    op.drop_index(op.f("ix_location_groups_parent_id"), table_name="location_groups")
    op.drop_column("location_groups", "parent_id")
    # ### end Alembic commands ###
