"""add index in bandwidth table

Revision ID: 62ae044c7668
Revises: 520d3574538a
Create Date: 2026-04-23 21:04:36.555343

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "62ae044c7668"
down_revision: Union[str, Sequence[str], None] = "520d3574538a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_device_bw_time",
        "device_bandwidth",
        ["device_id", "timestamp"],
        unique=False,
    )
    op.create_index(
        "idx_switch_bw_time",
        "switch_bandwidth",
        ["switch_id", "timestamp"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_switch_bw_time", table_name="switch_bandwidth")
    op.drop_index("idx_device_bw_time", table_name="device_bandwidth")
    # ### end Alembic commands ###
