"""add indexes

Revision ID: 92481f576b52
Revises: 4c5925e99075
Create Date: 2026-02-24 14:09:25.412425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92481f576b52'
down_revision: Union[str, Sequence[str], None] = '4c5925e99075'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_device_id'), 'alerts', ['device_id'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index(op.f('ix_devices_device_type'), 'devices', ['device_type'], unique=False)
    op.create_index(op.f('ix_devices_location_id'), 'devices', ['location_id'], unique=False)
    op.create_index(op.f('ix_devices_name'), 'devices', ['name'], unique=False)
    op.create_index(op.f('ix_devices_status'), 'devices', ['status'], unique=False)
    op.create_index(op.f('ix_devices_switch_id'), 'devices', ['switch_id'], unique=False)
    op.create_index(op.f('ix_locations_location_type'), 'locations', ['location_type'], unique=False)
    op.create_index(op.f('ix_locations_name'), 'locations', ['name'], unique=False)
    op.create_index('ix_status_history_node_changed', 'status_history', ['node_type', 'node_id', 'changed_at'], unique=False)
    op.create_index('ix_status_history_status', 'status_history', ['status'], unique=False)
    op.create_index(op.f('ix_switch_alerts_created_at'), 'switch_alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_switch_alerts_severity'), 'switch_alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_switch_alerts_status'), 'switch_alerts', ['status'], unique=False)
    op.create_index(op.f('ix_switch_alerts_switch_id'), 'switch_alerts', ['switch_id'], unique=False)
    op.create_index(op.f('ix_switches_ip_address'), 'switches', ['ip_address'], unique=False)
    op.create_index(op.f('ix_switches_location_id'), 'switches', ['location_id'], unique=False)
    op.create_index(op.f('ix_switches_name'), 'switches', ['name'], unique=False)
    op.create_index(op.f('ix_switches_node_id'), 'switches', ['node_id'], unique=False)
    op.create_index(op.f('ix_switches_status'), 'switches', ['status'], unique=False)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index(op.f('ix_switches_status'), table_name='switches')
    op.drop_index(op.f('ix_switches_node_id'), table_name='switches')
    op.drop_index(op.f('ix_switches_name'), table_name='switches')
    op.drop_index(op.f('ix_switches_location_id'), table_name='switches')
    op.drop_index(op.f('ix_switches_ip_address'), table_name='switches')
    op.drop_index(op.f('ix_switch_alerts_switch_id'), table_name='switch_alerts')
    op.drop_index(op.f('ix_switch_alerts_status'), table_name='switch_alerts')
    op.drop_index(op.f('ix_switch_alerts_severity'), table_name='switch_alerts')
    op.drop_index(op.f('ix_switch_alerts_created_at'), table_name='switch_alerts')
    op.drop_index('ix_status_history_status', table_name='status_history')
    op.drop_index('ix_status_history_node_changed', table_name='status_history')
    op.drop_index(op.f('ix_locations_name'), table_name='locations')
    op.drop_index(op.f('ix_locations_location_type'), table_name='locations')
    op.drop_index(op.f('ix_devices_switch_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_status'), table_name='devices')
    op.drop_index(op.f('ix_devices_name'), table_name='devices')
    op.drop_index(op.f('ix_devices_location_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_type'), table_name='devices')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_device_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    # ### end Alembic commands ###
