"""add location group table

Revision ID: 987383d25581
Revises: bcda08cbd6f3
Create Date: 2026-04-20 10:59:41.449748

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "987383d25581"
down_revision: Union[str, Sequence[str], None] = "bcda08cbd6f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "location_groups",
        sa.Column("group_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("group_id"),
    )
    op.create_index(
        op.f("ix_location_groups_name"), "location_groups", ["name"], unique=True
    )
    op.add_column("locations", sa.Column("group_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_locations_group_id"), "locations", ["group_id"], unique=False
    )
    op.create_foreign_key(
        "fk_locations_group_id_location_groups",
        "locations",
        "location_groups",
        ["group_id"],
        ["group_id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_locations_group_id_location_groups", "locations", type_="foreignkey"
    )
    op.drop_index(op.f("ix_locations_group_id"), table_name="locations")
    op.drop_column("locations", "group_id")
    op.drop_index(op.f("ix_location_groups_name"), table_name="location_groups")
    op.drop_table("location_groups")
    # ### end Alembic commands ###
