"""adding librenms link for switch and alerts

Revision ID: b2a181ddf243
Revises: 1751a813079b
Create Date: 2026-01-05 10:06:25.076945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2a181ddf243'
down_revision: Union[str, Sequence[str], None] = '1751a813079b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('librenms_alert_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_alerts_librenms_alert_id'), 'alerts', ['librenms_alert_id'], unique=False)
    op.add_column('devices', sa.Column('librenms_last_synced', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('devices', 'librenms_last_synched')
    op.add_column('switch_alerts', sa.Column('librenms_alert_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_switch_alerts_librenms_alert_id'), 'switch_alerts', ['librenms_alert_id'], unique=False)
    op.add_column('switches', sa.Column('librenms_device_id', sa.Integer(), nullable=True))
    op.add_column('switches', sa.Column('librenms_hostname', sa.String(length=255), nullable=True))
    op.add_column('switches', sa.Column('librenms_last_synced', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('switches', 'location_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_switches_librenms_device_id'), 'switches', ['librenms_device_id'], unique=True)
    op.create_index(op.f('ix_switches_librenms_hostname'), 'switches', ['librenms_hostname'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_switches_librenms_hostname'), table_name='switches')
    op.drop_index(op.f('ix_switches_librenms_device_id'), table_name='switches')
    op.alter_column('switches', 'location_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('switches', 'librenms_last_synced')
    op.drop_column('switches', 'librenms_hostname')
    op.drop_column('switches', 'librenms_device_id')
    op.drop_index(op.f('ix_switch_alerts_librenms_alert_id'), table_name='switch_alerts')
    op.drop_column('switch_alerts', 'librenms_alert_id')
    op.add_column('devices', sa.Column('librenms_last_synched', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('devices', 'librenms_last_synced')
    op.drop_index(op.f('ix_alerts_librenms_alert_id'), table_name='alerts')
    op.drop_column('alerts', 'librenms_alert_id')
    # ### end Alembic commands ###
