"""add index on alert and bandwidth table

Revision ID: b98ecd2c152b
Revises: ccc89121b183
Create Date: 2026-05-11 09:35:19.638363

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b98ecd2c152b"
down_revision: Union[str, Sequence[str], None] = "ccc89121b183"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_alerts_cleared_at"), "alerts", ["cleared_at"], unique=False
    )
    op.alter_column(
        "device_bandwidth",
        "timestamp",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.create_index(
        op.f("ix_switch_alerts_cleared_at"),
        "switch_alerts",
        ["cleared_at"],
        unique=False,
    )
    op.alter_column(
        "switch_bandwidth",
        "timestamp",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.create_index(
        "ix_device_bandwidth_device_time",
        "device_bandwidth",
        ["device_id", "timestamp"],
        unique=False,
    )
    op.create_index(
        "ix_switch_bandwidth_switch_time",
        "switch_bandwidth",
        ["switch_id", "timestamp"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_switch_bandwidth_switch_time", table_name="switch_bandwidth")
    op.drop_index("ix_device_bandwidth_device_time", table_name="device_bandwidth")
    op.alter_column(
        "switch_bandwidth",
        "timestamp",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.drop_index(op.f("ix_switch_alerts_cleared_at"), table_name="switch_alerts")
    op.alter_column(
        "device_bandwidth",
        "timestamp",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.drop_index(op.f("ix_alerts_cleared_at"), table_name="alerts")
    # ### end Alembic commands ###
