"""add waypoints to fo routes table

Revision ID: bcda08cbd6f3
Revises: 92481f576b52
Create Date: 2026-03-10 11:10:05.934461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcda08cbd6f3'
down_revision: Union[str, Sequence[str], None] = '92481f576b52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fo_routes', sa.Column('waypoints', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fo_routes', 'waypoints')
    # ### end Alembic commands ###
