"""add name field for network nodes

Revision ID: c4c2b47e1be6
Revises: df84cad23af4
Create Date: 2026-02-11 11:23:15.111382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4c2b47e1be6'
down_revision: Union[str, Sequence[str], None] = 'df84cad23af4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('network_nodes', sa.Column('name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('network_nodes', 'name')
    # ### end Alembic commands ###
