"""Add system config, thresholds rule, and user notification settings

Revision ID: ccc89121b183
Revises: 62ae044c7668
Create Date: 2026-05-06 13:52:37.924219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccc89121b183'
down_revision: Union[str, Sequence[str], None] = '62ae044c7668'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ping_frequency', sa.Integer(), nullable=False),
    sa.Column('ping_probe_count', sa.Integer(), nullable=False),
    sa.Column('ping_timeout_ms', sa.Integer(), nullable=False),
    sa.Column('offline_fail_required', sa.Integer(), nullable=False),
    sa.Column('recovery_success_required', sa.Integer(), nullable=False),
    sa.Column('alert_raise_streak', sa.Integer(), nullable=False),
    sa.Column('alert_clear_streak', sa.Integer(), nullable=False),
    sa.Column('history_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('history_retention_days', sa.Integer(), nullable=False),
    sa.Column('alert_retention_days', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('threshold_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_type', sa.String(length=100), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('warning_value', sa.Float(), nullable=False),
    sa.Column('critical_value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threshold_rules_device_type'), 'threshold_rules', ['device_type'], unique=False)
    op.create_table('user_notification_settings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('enable_popups', sa.Boolean(), nullable=False),
    sa.Column('notification_level', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_notification_settings')
    op.drop_index(op.f('ix_threshold_rules_device_type'), table_name='threshold_rules')
    op.drop_table('threshold_rules')
    op.drop_table('system_config')
    # ### end Alembic commands ###
