"""add is_uplink field to librenms_ports

Revision ID: df84cad23af4
Revises: f53751c8dd9a
Create Date: 2026-01-29 16:53:21.489749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df84cad23af4'
down_revision: Union[str, Sequence[str], None] = 'f53751c8dd9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('librenms_ports', sa.Column('is_uplink', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('librenms_ports', 'is_uplink')
    # ### end Alembic commands ###
