"""add acknowledged_at and resolution_note field to alerts

Revision ID: e8f54eef4bf7
Revises: b2a181ddf243
Create Date: 2026-01-21 10:17:05.015412

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e8f54eef4bf7"
down_revision: Union[str, Sequence[str], None] = "b2a181ddf243"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "alerts",
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column("alerts", sa.Column("resolution_note", sa.Text(), nullable=True))
    op.add_column(
        "switch_alerts",
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "switch_alerts", sa.Column("resolution_note", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("switch_alerts", "resolution_note")
    op.drop_column("switch_alerts", "acknowledged_at")
    op.drop_column("alerts", "resolution_note")
    op.drop_column("alerts", "acknowledged_at")
    # ### end Alembic commands ###
