"""add librenms_ports table

Revision ID: f53751c8dd9a
Revises: e8f54eef4bf7
Create Date: 2026-01-28 13:49:27.520108

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f53751c8dd9a"
down_revision: Union[str, Sequence[str], None] = "e8f54eef4bf7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "librenms_ports",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=True),
        sa.Column("switch_id", sa.Integer(), nullable=True),
        sa.Column("librenms_device_id", sa.Integer(), nullable=False),
        sa.Column("port_id", sa.Integer(), nullable=False),
        sa.Column("if_name", sa.String(length=255), nullable=False),
        sa.Column("if_type", sa.String(length=255), nullable=True),
        sa.Column("if_oper_status", sa.String(length=64), nullable=True),
        sa.Column("enabled", sa.Boolean(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["device_id"], ["devices.device_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["switch_id"], ["switches.switch_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("port_id", name="uq_librenms_ports_port_id"),
    )
    op.create_index(
        op.f("ix_librenms_ports_device_id"),
        "librenms_ports",
        ["device_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_librenms_ports_librenms_device_id"),
        "librenms_ports",
        ["librenms_device_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_librenms_ports_port_id"), "librenms_ports", ["port_id"], unique=False
    )
    op.create_index(
        op.f("ix_librenms_ports_switch_id"),
        "librenms_ports",
        ["switch_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_librenms_ports_switch_id"), table_name="librenms_ports")
    op.drop_index(op.f("ix_librenms_ports_port_id"), table_name="librenms_ports")
    op.drop_index(
        op.f("ix_librenms_ports_librenms_device_id"), table_name="librenms_ports"
    )
    op.drop_index(op.f("ix_librenms_ports_device_id"), table_name="librenms_ports")
    op.drop_table("librenms_ports")
    # ### end Alembic commands ###
